### ISSUE TITLE
[Bug|Crash]: Epic fight has failed to load correctly

### ISSUE THREAD

**Issue by Tobigb** [Yesssssman/epicfightmod#1532]
### Have you checked if a similar issue is already reported by someone else?

- [x] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [ ] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Server Mode

SinglePlayer

### Minecraft Version

1.20.1

### What happened?

![Captura](https://github.com/Yesssssman/epicfightmod/assets/158403619/9dbe535b-30e5-4aa1-b0e0-94839a900067)

**Comment by Tobigb** [comment]
I was trying to play with mods, should i send the mods list?

**Comment by MetalKnight56** [comment]
Outdated addons or mod incompatibility
